// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNytkVIX1rn-zClhmutNFHg8SLEsnnnto',
    appId: '1:1051849617610:web:8be73005764d10e1200433',
    messagingSenderId: '1051849617610',
    projectId: 'pay-and-buy-88aa7',
    authDomain: 'pay-and-buy-88aa7.firebaseapp.com',
    storageBucket: 'pay-and-buy-88aa7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFAfeeZCuz0ILAI-4Cqt5ub4K0OKmtDMk',
    appId: '1:1051849617610:android:3eb99abda9dcfac7200433',
    messagingSenderId: '1051849617610',
    projectId: 'pay-and-buy-88aa7',
    storageBucket: 'pay-and-buy-88aa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhe76SQWMYQ3vpX2nMxgwaT3kGcg25pcY',
    appId: '1:1051849617610:ios:9a79286d8f3ba871200433',
    messagingSenderId: '1051849617610',
    projectId: 'pay-and-buy-88aa7',
    storageBucket: 'pay-and-buy-88aa7.appspot.com',
    iosBundleId: 'com.example.payAndBuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhe76SQWMYQ3vpX2nMxgwaT3kGcg25pcY',
    appId: '1:1051849617610:ios:9a79286d8f3ba871200433',
    messagingSenderId: '1051849617610',
    projectId: 'pay-and-buy-88aa7',
    storageBucket: 'pay-and-buy-88aa7.appspot.com',
    iosBundleId: 'com.example.payAndBuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNytkVIX1rn-zClhmutNFHg8SLEsnnnto',
    appId: '1:1051849617610:web:960804e61886051b200433',
    messagingSenderId: '1051849617610',
    projectId: 'pay-and-buy-88aa7',
    authDomain: 'pay-and-buy-88aa7.firebaseapp.com',
    storageBucket: 'pay-and-buy-88aa7.appspot.com',
  );

}